name: PerformanceMetrics
version: '1.1.0'
main: cn.nyatu.sakimugi.performancemetrics.PerformanceMetricsPlugin
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  gpm:
    description: Query the current server MSPT and TPS.
    usage: /gpm
    permission: gpm.use
permissions:
  gpm.use:
    description: Allows using /gpm to view server performance metrics.
    default: true
